docker-build:
  needs: test
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: AWS認証情報を設定
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Amazon ECR にログイン
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker イメージをビルド
      run: |
        docker build -t fastapi-ci-practice .

    - name: ECRへPush
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker tag fastapi-ci-practice:latest $ECR_REGISTRY/fastapi-ci-practice:latest
        docker push $ECR_REGISTRY/fastapi-ci-practice:latest